### ISSUE TITLE
HttpError

### ISSUE THREAD

**Issue by DavidSongzw** [NarekA/git-notion#1]
* git-notion version:0.2.4
* Python version:3.9
* Operating System:Mac

### Description

run git-notion to upload doc

### What I Did

```
export NOTION_TOKEN_V2=xxxxx
export NOTION_ROOT_PAGE="https://www.notion.so/myspace/xxxxx?v=xxxxxx"
export NOTION_IGNORE_REGEX="android/.*|ios/.*|node_modules/.*"
git-notion
```

### Error

```
running sync
Traceback (most recent call last):
  File "/usr/local/bin/git-notion", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/git_notion/cli.py", line 12, in main
    git_notion.sync_to_notion(path)
  File "/usr/local/lib/python3.9/site-packages/git_notion/git_notion.py", line 63, in sync_to_notion
    root_page = get_client().get_block(root_page_url)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.9/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/usr/local/lib/python3.9/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.
```

**Comment by DavidSongzw** [comment]
And my NOTION_ROOT_PAGE link is like "https://www.notion.so/myspace/xxxxx?v=xxxxxx".When it is a full database page, everything is ok. If it is a normal page, the above error occurs.By the way my page is a subpage.

**Comment by NarekA** [comment]
@DavidSongzw If you submit this as a PR, I will merge this.

**Comment by DavidSongzw** [comment]
Sorry, I'm not a python programmer,it may be caused by notion-py, You can see his issues.

**Comment by gamcoh** [comment]
I think that's maybe because your page is private @DavidSongzw?

**Comment by mehdicopter** [comment]
I have the same issue. The workspace is private in deed.

**Comment by NicolasTobias** [comment]
Same error here, somehow it worked but no more.

**Comment by yechielw** [comment]
It seems like you have to you a root page as a sub-page throughs an error.
<img width="1168" alt="Screen Shot 2022-02-06 at 20 18 50" src="https://user-images.githubusercontent.com/41305372/152695377-1b8ea2d4-1919-49d5-933b-0d400c0bb29b.png">

**Comment by yechielw** [comment]
@DavidSongzw

**Comment by afreitasdotdev** [comment]
Same error here. Im try in root page and sub-page, both dont work.

**Comment by olliechick** [comment]
I've started getting this issue today, to the same page that worked a few days ago.

**Comment by Seth-Williams** [comment]
just started using git-notion and having the same error today

**Comment by andrewspode** [comment]
Has there been any movement on this issue? I don't have the option of making a top-level page as it's a large company Notion space. It would need to be a sub-page. 

Are there any plans to fix this? Is there any way I can help?

**Comment by andrewspode** [comment]
I've stepped through the code and traced this back to an issue in the underlying Notion API package. It's caused by "limit" being set too high. For some reason the fix hasn't been merged in (I've nudged) but you can fix it yourself by changing the limit in client.py from 10000 to 100.

https://github.com/knightjoel/notion-py/commit/521013095e96a05b80edd3e007c931c78a55ce6b

Hopefully this will be resolved.

**Comment by NarekA** [comment]
@andrewspode I can update this repo to use your fork of notion-py if that fixes this issue.

**Comment by NarekA** [comment]
If someone can verify that [this](https://github.com/NarekA/git-notion/pull/3) resolves the issue, I can merge it and publish the new version.

**Comment by andrewspode** [comment]
It's not my fix - it's someone elses, but I did fix it locally by installing that version after I had installed notion-py. I will find some time to test it this week.

**Comment by giannissmirnios** [comment]
Just tested and at the current latest version doesn't work - still the same error as seen above. However if you go to ~/.local/lib/python3.8/site-packages/notion and manually change `client.py` and `store.py` as seen [here](https://github.com/knightjoel/notion-py/commit/521013095e96a05b80edd3e007c931c78a55ce6b) then it works!

**Comment by Christos-Hadjinikolis** [comment]
Does not work.

**Comment by FMKerckhof** [comment]
> Just tested and at the current latest version doesn't work - still the same error as seen above. However if you go to ~/.local/lib/python3.8/site-packages/notion and manually change `client.py` and `store.py` as seen [here](https://github.com/knightjoel/notion-py/commit/521013095e96a05b80edd3e007c931c78a55ce6b) then it works!

this worked for me as well
